# Generated by Django 4.1.4 on 2022-12-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('QuestionId', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('Question', models.CharField(max_length=1000)),
            ],
        ),
    ]
