# Generated by Django 4.1.4 on 2022-12-29 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='Question',
            new_name='Text',
        ),
    ]
