# Generated by Django 4.1.4 on 2022-12-29 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_rename_question_questions_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='QuestionId',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='Text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='Title',
            new_name='title',
        ),
    ]
