# Generated by Django 4.1.4 on 2023-01-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_rename_questionid_questions_question_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
